# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  sproto_config = debug
  lpeg_config = debug
  math3d_config = debug

else ifeq ($(config),release)
  sproto_config = release
  lpeg_config = release
  math3d_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := sproto lpeg math3d

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

sproto:
ifneq (,$(sproto_config))
	@echo "==== Building sproto ($(sproto_config)) ===="
	@${MAKE} --no-print-directory -C build/projects/sproto -f Makefile config=$(sproto_config)
endif

lpeg:
ifneq (,$(lpeg_config))
	@echo "==== Building lpeg ($(lpeg_config)) ===="
	@${MAKE} --no-print-directory -C build/projects/lpeg -f Makefile config=$(lpeg_config)
endif

math3d:
ifneq (,$(math3d_config))
	@echo "==== Building math3d ($(math3d_config)) ===="
	@${MAKE} --no-print-directory -C build/projects/math3d -f Makefile config=$(math3d_config)
endif

clean:
	@${MAKE} --no-print-directory -C build/projects/sproto -f Makefile clean
	@${MAKE} --no-print-directory -C build/projects/lpeg -f Makefile clean
	@${MAKE} --no-print-directory -C build/projects/math3d -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   sproto"
	@echo "   lpeg"
	@echo "   math3d"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"